######################## default configuration ####################
baseURL = "https://earnonlinemoney.org"
title = "Earn Money Online | Side Hustles, Work at Home Jobs, Passive Income Ideas"
theme = "geeky-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "8"
# post excerpt
summaryLength = "25"
# google analytics
googleAnalytics = "UA-151135138-1" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "earnonline" # get your shortname form here : https://disqus.com
autoHeadingID = true 
# Robotstxt
enableRobotsTXT = true

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.87.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
canonifyURLs = true

####################### Table of Contents ##########################

  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

############################ Links ###########################
[permalinks]
  categories = "/:slug/"
